### PR TITLE
feat(pbar): Add global progress bar to write to

### PR DESCRIPTION
**Pull request by mgattozzi**
This commit allows us to have a global progress bar to write data to
giving us the following benefits:

- Consistent ways to handle types of messages such as errors and
  warnings
- Easy interface to add progress bars of various types
- Easy to maintain, add new types of bars, or more while encapsulating
  the login in a single module

Output Preview:

wasm-pack

### CODE REVIEW

**Comment by mgattozzi** [comment]
@ashleygwilliams I'll need to rebase this and fix it all up now that we've done the warning stuff on Cargo.toml. Want me to do it after you do the style clean up? I can then use that here.

**Comment by ashleygwilliams** [comment]
@mgattozzi up to you- im probably not gonna be able to turn my attention to this until later so - if you wanna just clean it up so that i can merge it that's fine, that way you aren't blocked on me :)

**Comment by mgattozzi** [comment]
Awesome I'll rebase clean it up, then lets get it merged and you can work on all the styling stuff you wanted to do!

**Comment by mgattozzi** [comment]
Not the worse rebase, but not the easiest. Output still looks the same, but it would be good to just do a once over before merging just to be sure :)

**Comment by ashleygwilliams** [comment]
@mgattozzi that's on me :( thanks for struggling through... imma pull this local and poke it and then merge.

**Comment by mgattozzi** [comment]
@ashleygwilliams ? Nah there just was a lot of stuff changed so it was expected, in fact it gave me a reason to clean up some of the code so it's all good! :D let me know if you want anything changed otherwise meeeerge it :D

**Comment by ashleygwilliams** [comment]
it is done. THANK UUUUUU

**Pull request merged**
