### PR TITLE
Add a --target option target different environment (nodejs, browser)

### PR DESCRIPTION
**Pull request by djfarly**
Implements #75 

I had some time in the train – I hope it's okay.
Some lines of documentation and a few line breaks for readability included.

Thoughts?

Make sure these boxes are checked! 📦✅

- [x] You have the latest version of `rustfmt` installed and have your 
      cloned directory set to nightly
```bash
$ rustup override set nightly
$ rustup component add rustfmt-preview --toolchain nightly
```
- [x] You ran `rustfmt` on the code base before submitting
- [x] You reference which issue is being closed in the PR text

✨✨ 😄 Thanks so much for contributing to wasm-pack! 😄 ✨✨

### CODE REVIEW

**Comment by djfarly** [comment]
i'll look at rustfmt in a minute

**Comment by mgattozzi** [comment]
This LGTM, I think we just need you to format it with the latest rustfmt :)

**Comment by djfarly** [comment]
Does the update meet your expectations a bit more closely?

**Comment by djfarly** [comment]
I'm not quite sure why travis fails - I tried updating rustfmt…

The log says:
```
0.10s$ cargo fmt -- --write-mode diff
Unrecognized option: 'write-mode'
```

🤔

**Comment by ashleygwilliams** [comment]
@djfarly - no worries on "stealing", i meant it more as an apology for filing a very vague feature issue 😅 

`--target` sounds great to me, it's both analogous to rust and webpack, which is perfect IMO. 

FYI the travis failure was a breaking change in rustfmt that we(lol, actually YOU! https://github.com/ashleygwilliams/wasm-pack/pull/128) fixed.

as for what should be supported- you can see the flags here: https://github.com/rustwasm/wasm-bindgen#cli-reference. i agree that the docs are a bit unwiedly to navigate- which is partially why wrapping wasm-bindgen up into wasm-pack will hopefully make it an easier user experience!

i'm gonna take a slightly closer look at this- but i think we should probably be able to merge this today, or at least in the next few days! thank you so much for your efforts on this!!

**Comment by ashleygwilliams** [comment]
slurped this up, rebased it, added docs in https://github.com/ashleygwilliams/wasm-pack/pull/132.

**Pull request closed without merging**
