### PR TITLE
[WIP] feat(manifest): author data from npmrc

### LINKED ISSUE #2: author data?
we can grab author data from Cargo as well, but we MIGHT consider checking if there is an `.npmrc` and preferring that if it exists

### PR DESCRIPTION
**Pull request by ashleygwilliams**
✨👾 WIP; do no merge 👾 ✨ 

fixes #2

### CODE REVIEW

**Comment by sendilkumarn** [comment]
Does it includes fallback to cargo author when there is no .npmrc file?

**Comment by ashleygwilliams** [comment]
not yet! it falls back to `""` but i will add that now :D. 

also: just filed https://github.com/yoshuawuyts/npmrc/issues/2

**Comment by ashleygwilliams** [comment]
hrm @sendilkumarn - this is actually a *lil* tricky, as Crates support an authors vector... should i just pick the first one? or do you think it's better to leave it as an empty string? i'm torn.

**Comment by sendilkumarn** [comment]
the first one makes sense. I was stuck at the same point. or intelligent identification based on the computer name. well let it be empty whn the length is more than one.

**Comment by ashleygwilliams** [comment]
yeah ok cool. thanks for workshopping that with me ☺️

**Comment by ashleygwilliams** [comment]
closing in favor of a new PR as this is from a very old version of the project and not worth the merge

**Pull request closed without merging**
