### PR TITLE
add dir_diff test

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Tests a full directory, rather than a single file. Ref: https://github.com/ashleygwilliams/wasm-pack/issues/18#issuecomment-370895435. Thanks!

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@ashleygwilliams done!

**Comment by yoshuawuyts** [comment]
@ashleygwilliams thinking we could merge this in as-is, and perhaps rebase the other branch onto this and add a test there. Would make it feel more of a whole, and set a new standard for PRs to this repo :sparkles:

**Comment by ashleygwilliams** [comment]
@yoshuawuyts yes that is a very good idea, on it!

**Comment by yoshuawuyts** [comment]
woot!

**Pull request merged**
